services:
  db:
    restart: always
    build:
      context: .
      dockerfile: db.Dockerfile
      tags:
        - pypi_scraper/db
    ports:
      - '5432:5432'
    networks:
      - db_net
    environment:
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: defaultdb
    volumes:
      - db:/var/lib/postgresql/data
      - './sql:/docker-entrypoint-initdb.d/'

  app:
    restart: always
    build:
      context: .
      dockerfile: app.Dockerfile
      tags:
        - pypi_scraper/app
    networks:
      - db_net
    environment:
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: defaultdb
      POSTGRES_HOST: db
    depends_on:
      - db

volumes:
  db:

networks:
  db_net:
