services:
  db:
    restart: always
    image: rpi-cluster-4b-1gb-1:5000/pypi_scraper/db:${STACK_VERSION:-latest}
    networks:
      - db_net
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: defaultdb
    deploy:
      restart_policy:
        condition: any
      placement:
          constraints:
            - node.labels.role==db
    volumes:
      - /mnt/ssd/postgres:/var/lib/postgresql/data

  broker:
    restart: always
    image: rabbitmq:3-management-alpine
    networks:
      - broker_net
    ports:
      - '8080:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: pypi_scraper
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: pypi_scraper
    deploy:
      restart_policy:
        condition: any
      placement:
          constraints:
            - node.labels.role==broker
    volumes:
      - broker:/var/lib/postgresql/data

  kpn_processor:
    image: rpi-cluster-4b-1gb-1:5000/pypi_scraper/app:${STACK_VERSION:-latest}
    command: ["python", "src/pipdepgraph/entrypoints/process_known_package_names_rmq.py"]
    deploy:
      restart_policy:
        condition: any
      replicas: 16
      placement:
        constraints:
          - node.labels.role==app
    networks:
      - db_net
      - broker_net
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: defaultdb
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD: password
      RABBITMQ_HOST: broker
      RABBITMQ_VHOST: pypi_scraper
      RABBITMQ_USERNAME: pypi_scraper
      RABBITMQ_PASSWORD: password
      RABBITMQ_CTAG_PREFIX: "kpn_processor.{{.Task.Slot}}."
    depends_on:
      - db
      - broker

  vd_processor:
    image: rpi-cluster-4b-1gb-1:5000/pypi_scraper/app:${STACK_VERSION:-latest}
    deploy:
      restart_policy:
        condition: any
      replicas: 16
      placement:
        constraints:
          - node.labels.role==app
    command: ["python", "src/entrypoints/process_version_distributions_rmq.py"]
    networks:
      - db_net
      - broker_net
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: defaultdb
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD: password
      RABBITMQ_HOST: broker
      RABBITMQ_VHOST: pypi_scraper
      RABBITMQ_USERNAME: pypi_scraper
      RABBITMQ_PASSWORD: password
      RABBITMQ_CTAG_PREFIX: "vd_processor.{{.Task.Slot}}."
    depends_on:
      - db
      - broker

  pypi_loader:
    image: rpi-cluster-4b-1gb-1:5000/pypi_scraper/app:${STACK_VERSION:-latest}
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 0
      placement:
        constraints:
          - node.labels.role==app
    command: ["python", "src/pipdepgraph/entrypoints/load_from_pypi_simple_index.py"]
    networks:
      - db_net
      - broker_net
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: defaultdb
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD: password
      RABBITMQ_HOST: broker
      RABBITMQ_VHOST: pypi_scraper
      RABBITMQ_USERNAME: pypi_scraper
      RABBITMQ_PASSWORD: password
      RABBITMQ_CTAG_PREFIX: "pypi_loader.{{.Task.Slot}}."
      UPL_LOAD_VERSION_DISTRIBUTIONS: "true"
      UPL_LOAD_PACKAGE_NAMES: "false"
    depends_on:
      - db
      - broker

networks:
  db_net:
  broker_net:

volumes:
  broker:
