services:
  broker:
    restart: always
    image: rabbitmq:3-management-alpine
    networks:
      - broker_net
    ports:
      - '8080:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: pypi_scraper
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: pypi_scraper
    deploy:
      restart_policy:
        condition: any
      placement:
          constraints:
            - node.labels.role==broker
    volumes:
      - broker:/var/lib/rabbitmq

  names_processor:
    image: rpi-cluster-4b-1gb-1:5000/pypi_scraper/app:${STACK_VERSION:-latest}
    command: ["python", "src/pipdepgraph/entrypoints/process_package_names_rmq.py"]
    deploy:
      restart_policy:
        condition: any
      replicas: 24
      placement:
        constraints:
          - node.labels.role==app
    networks:
      - broker_net
    environment:
      POSTGRES_HOST: 172.105.159.14
      POSTGRES_DB: defaultdb
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

      RABBITMQ_HOST: broker
      RABBITMQ_VHOST: pypi_scraper
      RABBITMQ_USERNAME: pypi_scraper
      RABBITMQ_PASSWORD: password
      RABBITMQ_CTAG_PREFIX: "names_processor.{{.Task.Slot}}."
    depends_on:
      - broker
    secrets:
      - db_password

  dists_processor:
    image: rpi-cluster-4b-1gb-1:5000/pypi_scraper/app:${STACK_VERSION:-latest}
    deploy:
      restart_policy:
        condition: any
      replicas: 24
      placement:
        constraints:
          - node.labels.role==app
    command: ["python", "src/pipdepgraph/entrypoints/process_distributions_rmq.py"]
    networks:
      - broker_net
    environment:
      POSTGRES_HOST: 172.105.159.14
      POSTGRES_DB: defaultdb
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

      RABBITMQ_HOST: broker
      RABBITMQ_VHOST: pypi_scraper
      RABBITMQ_USERNAME: pypi_scraper
      RABBITMQ_PASSWORD: password
      RABBITMQ_CTAG_PREFIX: "dists_processor.{{.Task.Slot}}."
    depends_on:
      - broker
    secrets:
      - db_password

  unprocessed_record_loader:
    image: rpi-cluster-4b-1gb-1:5000/pypi_scraper/app:${STACK_VERSION:-latest}
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.labels.role==broker
    command: ["python", "src/pipdepgraph/entrypoints/unprocessed_record_loader_rmq.py"]
    networks:
      - broker_net
    environment:
      POSTGRES_HOST: 172.105.159.14
      POSTGRES_DB: defaultdb
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

      RABBITMQ_HOST: broker
      RABBITMQ_VHOST: pypi_scraper
      RABBITMQ_USERNAME: pypi_scraper
      RABBITMQ_PASSWORD: password

      UPL_LOAD_DISTRIBUTIONS: "true"
      UPL_ONLY_LOAD_BDIST_WHEEL_DISTRIBUTIONS: "true"
      UPL_LOAD_PACKAGE_NAMES: "false"
      UPL_LOAD_INCOMPLETE_REQUIREMENTS: "false"
    depends_on:
      - broker
    secrets:
      - db_password

  pypi_loader:
    image: rpi-cluster-4b-1gb-1:5000/pypi_scraper/app:${STACK_VERSION:-latest}
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.labels.role==broker
    command: ["python", "src/pipdepgraph/entrypoints/load_from_pypi_simple_index.py"]
    networks:
      - broker_net
    environment:
      POSTGRES_HOST: 172.105.159.14
      POSTGRES_DB: defaultdb
      POSTGRES_USER: pypi_scraper
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      RABBITMQ_HOST: broker
      RABBITMQ_VHOST: pypi_scraper
      RABBITMQ_USERNAME: pypi_scraper
      RABBITMQ_PASSWORD: password
      RABBITMQ_CTAG_PREFIX: "pypi_loader.{{.Task.Slot}}."
    depends_on:
      - broker
    secrets:
      - db_password

networks:
  broker_net:
    driver: bridge

volumes:
  broker:

secrets:
  db_password:
    file: ./secrets/db_password
