services:
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: defaultdb
      POSTGRES_USER: pypi_scraper
      # Temporary default password. This was changed manually later.
      POSTGRES_PASSWORD: password
    # The environment uses docker compose, not swarm. However the file contains a swarm config in parallel just in case.
    restart: always
    deploy:
      restart_policy:
        condition: any
      placement:
          constraints:
            - node.labels.role==linode_db
    volumes:
      - /mnt/pypi-scraper-db-volume/postgres:/var/lib/postgresql/data
